services:
  - type: web
    name: ai-web-agent
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn webapp:app --bind 0.0.0.0:10000"
    plan: free
    envVars:
      - key: PORT
        value: 10000 